default:
  db_connection:
    driver: "ODBC Driver 17 for SQL Server"
    server: "T1PRANMSQL\\SQLPROD,60125"
    database: "MA_SDT_NS_DATA"
    uid: ""
    pwd: ""
    trusted: "Yes"
    sql_warehouse_id: !expr Sys.getenv("DATABRICKS_SQL_WAREHOUSE_ID")
    catalog: "catalog_40_copper_statistics_services"
    schema: "analytics_app"

production:
  db_connection:
    driver: "ODBC Driver 17 for SQL Server"
    server: "T1PRANMSQL.ad.hq.dept,60125"
    database: "MA_SDT_NS_DATA"
    uid: !expr Sys.getenv("SDT_UID")
    pwd: !expr Sys.getenv("SDT_PWD")
    trusted: "No"
    sql_warehouse_id: !expr Sys.getenv("DATABRICKS_SQL_WAREHOUSE_ID")
    catalog: "catalog_40_copper_statistics_services"
    schema: "analytics_app"
