name: update locale and lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '20 3 * * 0'

jobs:
  setup-locale:
    runs-on: ubuntu-latest
    steps:
      - name: Generate en_GB.UTF-8 locale
        run: |
          sudo locale-gen en_GB.UTF-8
          sudo update-locale LANG=en_GB.UTF-8
          echo "Locale set to en_GB.UTF-8"

  lint:
    needs: setup-locale
    uses: dfe-analytical-services/dfeshiny/.github/workflows/lintr_reusable.yaml@main
    with:
      is_package: "false"
    secrets:
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
